services:
  playground:
    build:
      context: ..
      dockerfile: playground/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - playground_bundles:/go/src/app/playground/bundles
    restart: unless-stopped

volumes:
  playground_bundles:
